/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
/**
 * デフォルトのクラス
 */
public class App {
    /**
     * コンストラクタ。特に実装することはないがjavadocの生成でエラーとなるので記述した
     */
    public App(){

    }
    /**
     * お試しメソッド
     * @return "Hello World!"
     */
    public String getGreeting() {
        return "Hello World!";
    }
    /**
     * お試しメソッド
     * @param args お試しファイル
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
